const getError = () => {
  throw Error('Error generating custom hook! Check if the input has been filled.')
}

module.exports = getError
